In [5]:
#from IPython.lib.pretty import Breakable
import numpy as np
import sympy as sp
data=[[32,400,20,95],
 [35,395,22,88],
 [38,390,25,80],
 [40,385,28,70],
 [42,380,30,60],
 [45,375,32,48]]
print("-----TASK 1-ANALYSIS USING PYTHON BASICS-----")
print("1.Sensor Readings:")
for i in data:
    print("Readings:",i)
print("2.Identify high temperature")
for i in data:
  if i[0]>40:
    print(i[0],"High Temperature Alert")
  else:
    print(i[0],"Temperature Normal")
print("3.Identify low battery")
for i in data:
  if i[3]<50:
    print(i[3],"Low Battery Alert")
  else:
    print(i[3],"Battery Charge Normal")
print("Function based on Status:")
def Battery_status(C):
  if C>70:
    return "High"
  elif C>=50:
    return "Medium"
  else:
    return "Low"
print("Status:",[Battery_status(i[3]) for i in data])
print("-----TASK 2- ANALYSIS USING NUMPY-----")
d=np.array(data)
print("D=\n",d)
print("Shape of the array: ",d.shape)
print("Average of each parameter")
print("Temperature=",np.mean(d[:,0]))
print("Voltage=",np.mean(d[:,1]))
print("Current=",np.mean(d[:,2]))
print("Charge=",np.mean(d[:,3]))
print("Minimum and Maximum Temperature:")
print("T_max:",np.max(d[:,0]))
print("T_min:",np.min(d[:,0]))
print("Voltage cloumn:",np.array(d[:,1]))
print("High_temperature Readings")
print("T>40=",d[d[:,0]>40])
print("Low_battery Readings")
print("C<50=",d[d[:,3]<50])
print("-----TASK 3-ANALYSIS USING LINEAR ALGEBRA-----")
A=np.array([[2,1],[1,3]])
X=np.array([[40],[25]])
Y=np.dot(A,X)
print("Y=",Y)
print("Transpose:\n",A.T)
det_A=np.linalg.det(A)
print("Determinant:",det_A)
inv_A=np.linalg.inv(A)
print("Inverse:\n",inv_A)
print("Solving 2x + y = 100,x + 3y = 120")
A2=np.array([[2,1],[1,3]])
B=np.array([100,120])
sol=np.linalg.solve(A2,B)
print("Solution:",sol)
x=sol[0]
y=sol[1]
print(f"solution:x={x:.2f},y={y:.2f}")
print("-----TASK-4:ANALYSIS USING CALCULUS-----")
t=sp.symbols('t')
C=100-2*t-0.5*t**2
deriv=sp.diff(C,t)
print("Rate of change dC/dt:",deriv)
t2=deriv.subs(t,2)
t5=deriv.subs(t,5)
print("Discharge rate:")
print("at t=2",t2)
print("at t=4",t5)
if t2==t5:
  print("Constant rate")
elif t2<t5:
  print("Increasing rate")
else:
  print("Decreasing rate")
print("---Final Analysis and Decision---")
time=[0,1,2,3,4,5]
temperature=[32,35,38,40,42,45]
charge=[95,88,80,70,60,48]
for i in range(len(time)):
    if temperature[i] > 40:
        print("\nTemperature first exceeds 40°C at:",time[i], "hours")
        break
charge_loss = charge[0] - charge[-1]
print("Total Charge Reduction:", charge_loss, "%")
print("Average Temperature:", np.mean(d[:,0]))
print("Average Voltage:", np.mean(d[:,1]))
print("Average Current:", np.mean(d[:,2]))
print("Average Charge:", np.mean(d[:,3]))
print("\nTransformed Output Y:")
print(Y)
print("\nSystem Solution:")
print("x =", sol[0])
print("y =", sol[1])
print("\nBattery discharge rate increases with time.")
print("The negative value of dC/dt shows that the battery is losing charge.")
print("\nFINAL DECISION: MONITOR")
print("Reason: Temperature exceeds 40°C and battery charge drops below 50%.")


-----TASK 1-ANALYSIS USING PYTHON BASICS-----
1.Sensor Readings:
Readings: [32, 400, 20, 95]
Readings: [35, 395, 22, 88]
Readings: [38, 390, 25, 80]
Readings: [40, 385, 28, 70]
Readings: [42, 380, 30, 60]
Readings: [45, 375, 32, 48]
2.Identify high temperature
32 Temperature Normal
35 Temperature Normal
38 Temperature Normal
40 Temperature Normal
42 High Temperature Alert
45 High Temperature Alert
3.Identify low battery
95 Battery Charge Normal
88 Battery Charge Normal
80 Battery Charge Normal
70 Battery Charge Normal
60 Battery Charge Normal
48 Low Battery Alert
Function based on Status:
Status: ['High', 'High', 'High', 'Medium', 'Medium', 'Low']
-----TASK 2- ANALYSIS USING NUMPY-----
D=
 [[ 32 400  20  95]
 [ 35 395  22  88]
 [ 38 390  25  80]
 [ 40 385  28  70]
 [ 42 380  30  60]
 [ 45 375  32  48]]
Shape of the array:  (6, 4)
Average of each parameter
Temperature= 38.666666666666664
Voltage= 387.5
Current= 26.166666666666668
Charge= 73.5
Minimum and Maximum Temperature:
T_max: 45
T